from weasyprint import HTML
from datetime import datetime
from typing import Dict
import base64

def generate_audit_pdf(inspection: Dict, shap: Dict, routing: Dict) -> bytes:
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: sans-serif; margin: 40px; }}
            h1 {{ color: #1f4e79; border-bottom: 2px solid #ddd; padding-bottom: 10px; }}
            .meta {{ background: #f9f9f9; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
            .driver {{ display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px dashed #ccc; }}
            .driver:last-child {{ border-bottom: none; }}
            .badge {{ padding: 4px 8px; border-radius: 4px; color: white; font-weight: bold; }}
            .confident {{ background: #28a745; }} .uncertain {{ background: #ffc107; color: #333; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ padding: 8px; border: 1px solid #ddd; text-align: left; }}
            th {{ background: #f4f4f4; }}
            .footer {{ margin-top: 40px; font-size: 10px; color: #888; text-align: center; }}
        </style>
    </head>
    <body>
        <h1>🔍 RefurbCortex AI | Audit Report</h1>
        <div class="meta">
            <strong>Inspection ID:</strong> {inspection.get('inspection_id', 'N/A')}<br>
            <strong>Timestamp:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>
            <strong>Routing:</strong> <span class="badge {'confident' if routing.get('status')=='CONFIDENT' else 'uncertain'}">{routing.get('status', 'UNKNOWN')}</span>
        </div>
        
        <h2>📊 SHAP Cost Attribution</h2>
        <table>
            <tr><th>Feature</th><th>Value</th><th>Contribution (₹)</th><th>Impact</th></tr>
            {''.join(f"<tr><td>{d['feature']}</td><td>{d['input_value']}</td><td>₹{d['contribution_inr']:,.0f}</td><td>{d['impact']}</td></tr>" for d in shap.get('top_drivers', []))}
        </table>
        
        <h2>⚖️ System 2 Recommendation</h2>
        <p><strong>Action:</strong> {inspection.get('recommendation', {}).get('recommendation', 'N/A')}</p>
        <p><strong>Reasoning:</strong> {inspection.get('recommendation', {}).get('reasoning', 'N/A')}</p>
        
        <div class="footer">
            Generated by RefurbCortex AI v0.3 | Audit Trail ID: {inspection.get('inspection_id', 'UNKNOWN')}
        </div>
    </body>
    </html>
    """
    return HTML(string=html).write_pdf()